# -*- coding: utf-8 -*-
"""PyTorch_CIFAR_10_ResNet18_dendrite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmTLj8sgffwM1LfkJR31GteVi2t6r1rW
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!rm -rf PerforatedAI
!git clone https://github.com/PerforatedAI/PerforatedAI.git
# %cd /content/PerforatedAI
!pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PerforatedAI
!pip install -q -e .

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/PerforatedAI
!mkdir -p Examples/hackathonProjects/cifar10-resnet18-dendrites
!ls Examples/hackathonProjects

!ls -lah Examples/hackathonProjects/cifar10-resnet18-dendrites/

# Commented out IPython magic to ensure Python compatibility.
# %%writefile Examples/hackathonProjects/cifar10-resnet18-dendrites/cifar10_resnet18_perforatedai.py
# import torch
# import torch.nn as nn
# from torch.utils.data import DataLoader
# import torchvision
# import torchvision.transforms as transforms
# from torchvision.models import resnet18
# 
# from perforatedai import globals_perforatedai as GPA
# from perforatedai import utils_perforatedai as UPA
# 
# DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
# 
# BATCH_SIZE = 128
# LR = 1e-3
# NUM_WORKERS = 2
# MAX_EPOCHS = 500
# 
# train_transform = transforms.Compose([
#     transforms.RandomCrop(32, padding=4),
#     transforms.RandomHorizontalFlip(),
#     transforms.ToTensor(),
#     transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
# ])
# 
# test_transform = transforms.Compose([
#     transforms.ToTensor(),
#     transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2470, 0.2435, 0.2616))
# ])
# 
# train_dataset = torchvision.datasets.CIFAR10(root="./data", train=True, download=True, transform=train_transform)
# test_dataset  = torchvision.datasets.CIFAR10(root="./data", train=False, download=True, transform=test_transform)
# 
# train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
# test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)
# 
# model = resnet18(weights=None)
# model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
# model.maxpool = nn.Identity()
# model.fc = nn.Linear(model.fc.in_features, 10)
# 
# # ✅ avoid debugger prompts for unwrapped BatchNorm
# GPA.pc.set_unwrapped_modules_confirmed(True)
# 
# # ✅ FORCE disable dendrite capacity test (REAL experiment)
# GPA.pc.set_testing_dendrite_capacity(False)
# GPA.pc.testing_dendrite_capacity = False
# 
# # ✅ initialize BEFORE moving to GPU
# model = UPA.initialize_pai(model)
# model = model.to(DEVICE)
# 
# criterion = nn.CrossEntropyLoss()
# 
# GPA.pai_tracker.set_optimizer(torch.optim.Adam)
# GPA.pai_tracker.set_scheduler(torch.optim.lr_scheduler.ReduceLROnPlateau)
# 
# optimArgs = {"params": model.parameters(), "lr": LR}
# schedArgs = {"mode": "max", "patience": 5}
# 
# optimizer, PAIscheduler = GPA.pai_tracker.setup_optimizer(model, optimArgs, schedArgs)
# 
# def test_accuracy(model):
#     model.eval()
#     correct = 0
#     total = 0
#     with torch.no_grad():
#         for images, labels in test_loader:
#             images, labels = images.to(DEVICE), labels.to(DEVICE)
#             outputs = model(images)
#             _, preds = outputs.max(1)
#             total += labels.size(0)
#             correct += preds.eq(labels).sum().item()
#     return 100.0 * correct / total
# 
# print("Using device:", DEVICE)
# print("Starting REAL Dendritic Optimization training...")
# 
# epoch = 0
# while True:
#     epoch += 1
#     model.train()
# 
#     running_loss = 0.0
#     correct = 0
#     total = 0
# 
#     for images, labels in train_loader:
#         images, labels = images.to(DEVICE), labels.to(DEVICE)
# 
#         optimizer.zero_grad()
#         outputs = model(images)
#         loss = criterion(outputs, labels)
#         loss.backward()
#         optimizer.step()
# 
#         running_loss += loss.item() * images.size(0)
#         _, preds = outputs.max(1)
#         total += labels.size(0)
#         correct += preds.eq(labels).sum().item()
# 
#     train_loss = running_loss / total
#     train_acc = 100.0 * correct / total
# 
#     test_acc = test_accuracy(model)
#     GPA.pai_tracker.add_test_score(test_acc, "Test Accuracy")
# 
#     model, restructured, training_complete = GPA.pai_tracker.add_validation_score(
#         test_acc,
#         model
#     )
#     model = model.to(DEVICE)
# 
#     print(f"Epoch [{epoch}] Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}% | Test Acc: {test_acc:.2f}%")
# 
#     if restructured:
#         optimArgs = {"params": model.parameters(), "lr": LR}
#         schedArgs = {"mode": "max", "patience": 5}
#         optimizer, PAIscheduler = GPA.pai_tracker.setup_optimizer(model, optimArgs, schedArgs)
# 
#     if training_complete:
#         print("PerforatedAI training complete. Stopping.")
#         break
# 
#     if epoch >= MAX_EPOCHS:
#         print("Reached MAX_EPOCHS safety limit. Stopping.")
#         break
# 
# print("Final Test Accuracy:", test_accuracy(model))
# print("Graph saved at: PAI/PAI.png")
#

!python Examples/hackathonProjects/cifar10-resnet18-dendrites/cifar10_resnet18_perforatedai.py